language: node_js
# node_js:
  # - 8

# before_script:
  # - "npm install" 
services: 
  - docker
before_install:
  - docker build -t test .
  - docker images
script:
  - docker run -d -p 3000:3000 test